const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:4000/api/v1";

/**
 * Fetch all project recommendations generated by the authenticated student.
 * @returns {Promise<Object>} API response with recommendations array in data
 */
export async function getStudentRecommendations() {
  const response = await fetch(`${API_BASE_URL}/recommendations`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
    credentials: "include",
  });

  let data;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const error = new Error(
      data?.message || "Failed to fetch project recommendations"
    );
    error.status = response.status;
    error.data = data;
    throw error;
  }

  return data;
}

/**
 * Generate a new AI-powered project recommendation.
 * @param {Object} params
 * @param {string[]} params.skills
 * @param {string} params.domain
 * @param {number} params.teamSize
 * @param {"BEGINNER"|"INTERMEDIATE"|"ADVANCED"} params.difficulty
 * @param {"ACADEMIC"|"REAL_WORLD"|"INNOVATIVE"|"RESEARCH"} params.projectType
 * @returns {Promise<Object>} API response with generated recommendation in data
 */
export async function createProjectRecommendation({
  skills,
  domain,
  teamSize,
  difficulty,
  projectType,
}) {
  const response = await fetch(`${API_BASE_URL}/recommendations`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    credentials: "include",
    body: JSON.stringify({
      skills,
      domain: domain.trim(),
      teamSize: Number(teamSize),
      difficulty,
      projectType,
    }),
  });

  let data;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const error = new Error(
      data?.message || "Failed to generate project recommendation"
    );
    error.status = response.status;
    error.data = data;
    throw error;
  }

  return data;
}

/**
 * Delete a previously generated recommendation.
 * @param {string} recommendationId
 * @returns {Promise<Object>} API response
 */
export async function deleteStudentRecommendation(recommendationId) {
  const response = await fetch(
    `${API_BASE_URL}/recommendations/${encodeURIComponent(recommendationId)}`,
    {
      method: "DELETE",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include",
    }
  );

  let data;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const error = new Error(
      data?.message || "Failed to delete project recommendation"
    );
    error.status = response.status;
    error.data = data;
    throw error;
  }

  return data;
}
