import { API_BASE_URL } from "@/utils/api";

// Fetch all project recommendations generated by the authenticated student.
export async function getStudentRecommendations() {
  const response = await fetch(`${API_BASE_URL}/recommendations`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
    credentials: "include",
  });

  let data;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const error = new Error(
      data?.message || "Failed to fetch project recommendations"
    );
    error.status = response.status;
    error.data = data;
    throw error;
  }

  return data;
}

// Generate a new AI-powered project recommendation.
export async function createProjectRecommendation({
  skills,
  domain,
  teamSize,
  difficulty,
  projectType,
}) {
  const response = await fetch(`${API_BASE_URL}/recommendations`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    credentials: "include",
    body: JSON.stringify({
      skills,
      domain: domain.trim(),
      teamSize: Number(teamSize),
      difficulty,
      projectType,
    }),
  });

  let data;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const error = new Error(
      data?.message || "Failed to generate project recommendation"
    );
    error.status = response.status;
    error.data = data;
    throw error;
  }

  return data;
}

// Delete a previously generated recommendation.
export async function deleteStudentRecommendation(recommendationId) {
  const response = await fetch(
    `${API_BASE_URL}/recommendations/${encodeURIComponent(recommendationId)}`,
    {
      method: "DELETE",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include",
    }
  );

  let data;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const error = new Error(
      data?.message || "Failed to delete project recommendation"
    );
    error.status = response.status;
    error.data = data;
    throw error;
  }

  return data;
}
