export const NOTIFICATION_TYPES = {
  PROJECT_PROPOSAL_SUBMITTED: "PROJECT_PROPOSAL_SUBMITTED",
  PROJECT_PROPOSAL_APPROVED: "PROJECT_PROPOSAL_APPROVED",
  PROJECT_PROPOSAL_REJECTED: "PROJECT_PROPOSAL_REJECTED",
  PROJECT_PROPOSAL_RESUBMITTED: "PROJECT_PROPOSAL_RESUBMITTED",
  PROJECT_ACCESS_REQUESTED: "PROJECT_ACCESS_REQUESTED",
  PROJECT_ACCESS_APPROVED: "PROJECT_ACCESS_APPROVED",
  PROJECT_ACCESS_REJECTED: "PROJECT_ACCESS_REJECTED",
};
